name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions/setup-rust@v1
      - name: Install dependencies
        run: cargo build --release
      - name: Get workspace members and run tests
        run: |
          workspaces=$(cargo metadata --format-version 1 | jq -r '.workspace.members[]')
          for workspace in $workspaces; do
            cargo test --manifest-path "$workspace/Cargo.toml"
          done
