name: "CI.rs test"

on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          component: clippy
      - run: cargo test --all-features
      - name: Run tests for each project
        run: cargo test --workspace --all-features -- --nocapture
