name: "Rust Simple CI"

on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          component: clippy
      - run: cargo test --all-features
      - name: Get workspace members and run tests
        run: |
          workspaces=$(cargo metadata --format-version 1 | jq -r '.workspace.members[]')
          for workspace in $workspaces; do
            cargo test --manifest-path "$workspace/Cargo.toml"
          done

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
